# Generated by Django 4.1.5 on 2023-01-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioanfibio',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='usuarioanfibio',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuarioanfibio',
            name='primer_nombre',
        ),
    ]
