# Generated by Django 4.1.5 on 2023-01-25 00:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0002_remove_usuarioanfibio_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRegistro',
            fields=[
                ('usuarioanfibio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('robotAnfibio.usuarioanfibio',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
