# Generated by Django 4.1.5 on 2023-01-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0003_usuarioregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioRegistro',
        ),
    ]
