# Generated by Django 4.1.5 on 2023-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0004_delete_usuarioregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarcacionesAnfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_embarcacion', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarioanfibio',
            name='codigo_usuario',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioanfibio',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
