# Generated by Django 4.1.5 on 2023-01-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0006_embarcacionesanfibio_imagen_embarcacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioanfibio',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
