# Generated by Django 4.1.5 on 2023-02-02 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotAnfibio', '0008_inspeccionesanfibio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionesanfibio',
            name='distancia_inspeccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inspeccionesanfibio',
            name='duracion_inspeccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inspeccionesanfibio',
            name='embarcacion_inspeccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inspeccionesanfibio',
            name='fecha_inspeccion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
